width: 10
height: 6
background_color: "white"
obstacle_color: "blue"
wall_color: [255,0,0]
obstacles:
  - 
    shape: "rectangle"
    width: 2
    height: 2
    position: [5,3]
    rotation: 0
  -
    shape: "circle"
    radius: 0.5
    position: [3,2]
  - 
    shape: "polygon"
    corners:
      - [0,1]
      - [0,2]
      - [1,2]
walls:
  - 
    start: [3,0]
    end:   [3,2]
  - 
    start: [3.5,4]
    end:   [3.5,6]
  -
    start: [10, 1.5]
    end:   [7, 1.5]
