  Map: "base.yaml"
  Robot:
    position: [0,0]
    width: 1
    height: 1
    theta: 0
    rightTorpedo: True # True = loaded
    leftTorpedo: True
    gripperState: False # False = open
  Items:
    - Wrench:
        image: "assets/wrench.png"
        position: [2,5]
        width: 0.3
        height: 0.6
    - Hammer:
        image: "assets/hammer.png"
        position: [9.5,0.25]
  TorpedoTargets:
    - LeftTorpedo:
        image: "assets/torpedo_board.png"
        position: [4.5,1]
        radius: 0.5
        blocked: True
    - RightTorpedo:
        image: "assets/torpedo_bowidth: 0.3
        height: 0.6ard.png"
        position: [5.5, 1]
        radius: 0.5
        blocked: False
  DropLocations:
    - WrenchDrop:
        image: "assets/drop_wrench.png"
        width: 1
        height: 1
        position: [8.5,2.5]
        receives: "Wrench"
        outcome:
          target: "LeftTorpedo"
          action: "UNBLOCK"
          reversible: True
    - HammerDrop:
        image: "assets/drop_hammer.png"
        position: [8.5, 3.5]
        width: 1
        height: 1
        receives: "Hammer"
        outcome:
          target: "RightTorpedo"
          action: "BLOCK"
          reversible: True
      
